-- Users Table
INSERT ALL
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (1, 'John', 'Doe', 'john.doe@example.com', 'password123', '123 Elm Street', '555-1234')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com', 'password456', '456 Oak Avenue', '555-5678')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (3, 'Emily', 'Johnson', 'emily.johnson@example.com', 'password789', '789 Pine Lane', '555-8765')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (4, 'Michael', 'Brown', 'michael.brown@example.com', 'password101', '101 Maple Road', '555-4321')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (5, 'Sarah', 'Davis', 'sarah.davis@example.com', 'password202', '202 Cedar Street', '555-9876')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (6, 'David', 'Wilson', 'david.wilson@example.com', 'password303', '303 Birch Avenue', '555-6543')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (7, 'Laura', 'Taylor', 'laura.taylor@example.com', 'password404', '404 Spruce Drive', '555-3210')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (8, 'James', 'Anderson', 'james.anderson@example.com', 'password505', '505 Fir Court', '555-1357')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (9, 'Jessica', 'Thomas', 'jessica.thomas@example.com', 'password606', '606 Elmwood Avenue', '555-2468')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (10, 'Robert', 'Jackson', 'robert.jackson@example.com', 'password707', '707 Oakwood Drive', '555-3579')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (11, 'Linda', 'White', 'linda.white@example.com', 'password808', '808 Pinewood Lane', '555-4680')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (12, 'William', 'Harris', 'william.harris@example.com', 'password909', '909 Maplewood Court', '555-5791')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (13, 'Olivia', 'Martin', 'olivia.martin@example.com', 'password010', '1010 Cedarwood Street', '555-6802')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (14, 'Daniel', 'Thompson', 'daniel.thompson@example.com', 'password111', '1111 Birchwood Drive', '555-7913')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (15, 'Sophia', 'Garcia', 'sophia.garcia@example.com', 'password212', '1212 Firwood Avenue', '555-8024')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (16, 'Matthew', 'Martinez', 'matthew.martinez@example.com', 'password313', '1313 Sprucewood Lane', '555-9135')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (17, 'Isabella', 'Robinson', 'isabella.robinson@example.com', 'password414', '1414 Pinewood Court', '555-0246')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (18, 'Alexander', 'Clark', 'alexander.clark@example.com', 'password515', '1515 Maplewood Avenue', '555-1357')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (19, 'Mia', 'Lewis', 'mia.lewis@example.com', 'password616', '1616 Oakwood Lane', '555-2468')
  INTO Users (UserID, FirstName, LastName, Email, Password, Address, PhoneNumber) VALUES (20, 'Ethan', 'Walker', 'ethan.walker@example.com', 'password717', '1717 Elmwood Street', '555-3579')
SELECT * FROM dual;

-- Products Table
INSERT ALL
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (1, 'Comfy Cat Bed', 'Soft and cozy cat bed.', 25.00, 50, 'Home', 4.5)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (2, 'Stylish Dog Collar', 'Durable and fashionable collar for dogs.', 12.00, 100, 'Accessories', 4.7)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (3, 'Interactive Cat Toy', 'Engaging toy for cats.', 20.00, 70, 'Toys', 4.6)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (4, 'Pet Grooming Brush', 'Brush for grooming pets.', 16.99, 60, 'Accessories', 4.4)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (5, 'Organic Dog Treats', 'Healthy treats for dogs.', 16.00, 90, 'Food', 4.8)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (6, 'Catnip Infused Toy', 'Toy infused with catnip.', 20.00, 50, 'Toys', 4.7)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (7, 'Pet Carrier Bag', 'Convenient carrier for pets.', 45.00, 30, 'Accessories', 4.5)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (8, 'Cozy Dog Blanket', 'Warm and cozy blanket for dogs.', 30.00, 40, 'Home', 4.6)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (9, 'Pet Travel Water Bottle', 'Portable water bottle for pets.', 26.00, 50, 'Accessories', 4.4)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (10, 'Dental Chew Toys', 'Chew toys for dental health.', 22.50, 80, 'Toys', 4.7)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (11, 'Luxury Pet Bed', 'High-end bed for pets.', 120.00, 20, 'Home', 4.8)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (12, 'Pet Hygiene Wipes', 'Wipes for cleaning pets.', 28.00, 70, 'Accessories', 4.6)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (13, 'Pet Stroller', 'Stroller for pets.', 35.99, 30, 'Accessories', 4.7)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (14, 'Automatic Feeder', 'Feeder with automatic timer.', 20.00, 50, 'Home', 4.5)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (15, 'Pet Puzzle Toy', 'Stimulating puzzle toy for pets.', 55.35, 40, 'Toys', 4.8)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (16, 'Pet Blanket', 'Soft blanket for pets.', 12.00, 100, 'Home', 4.6)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (17, 'Comfortable Pet Harness', 'Harness for pets.', 18.50, 60, 'Accessories', 4.7)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (18, 'Pet Cooling Mat', 'Cooling mat for hot days.', 30.00, 50, 'Home', 4.8)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (19, 'Pet Nail Clippers', 'Clippers for trimming nails.', 15.00, 90, 'Accessories', 4.5)
  INTO Products (ProductID, Name, Description, Price, StockLevel, Category, Rating) VALUES (20, 'Pet Bed with Removable Cover', 'Pet bed with removable cover for easy cleaning.', 50.00, 60, 'Home', 4.7)
SELECT * FROM dual;

-- ShoppingCarts Table
INSERT ALL
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (1, 1, TO_DATE('2024-01-15', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (2, 2, TO_DATE('2024-02-10', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (3, 3, TO_DATE('2024-03-05', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (4, 4, TO_DATE('2024-04-01', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (5, 5, TO_DATE('2024-05-07', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (6, 6, TO_DATE('2024-06-10', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (7, 7, TO_DATE('2024-07-05', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (8, 8, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (9, 9, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (10, 10, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (11, 11, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (12, 12, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (13, 13, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (14, 14, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (15, 15, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (16, 16, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (17, 17, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (18, 18, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (19, 19, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
  INTO ShoppingCarts (CartID, UserID, CreationDate) VALUES (20, 20, TO_DATE('2024-07-29', 'YYYY-MM-DD'))
SELECT * FROM dual;

-- ShoppingCartItems Table
INSERT ALL
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (1, 1, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (1, 2, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (2, 3, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (2, 4, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (3, 5, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (3, 6, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (4, 7, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (4, 8, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (5, 9, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (5, 10, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (6, 11, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (6, 12, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (7, 13, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (7, 14, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (8, 15, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (8, 16, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (9, 17, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (9, 18, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (10, 19, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (10, 20, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (11, 1, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (11, 2, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (12, 3, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (12, 4, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (13, 5, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (13, 6, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (14, 7, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (14, 8, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (15, 9, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (15, 10, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (16, 11, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (16, 12, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (17, 13, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (17, 14, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (18, 15, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (18, 16, 2)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (19, 17, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (19, 18, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (20, 19, 1)
  INTO ShoppingCartItems (CartID, ProductID, Quantity) VALUES (20, 20, 1)
SELECT * FROM dual;
